const SUPABASE_URL=(window.SEMSEM_CONFIG&&window.SEMSEM_CONFIG.url)||"";
const SUPABASE_ANON_KEY=(window.SEMSEM_CONFIG&&window.SEMSEM_CONFIG.anonKey)||"";
const sbReady=Boolean(window.supabase&&SUPABASE_URL&&SUPABASE_ANON_KEY);
const sb=sbReady?supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;

const START_CASH=500000, RENT_OFFLINE_CAP_MS=12*60*60*1000, DAY_MS=60*1000;
const initial=()=>({cash:START_CASH,rep:18,level:1,office:1,day:1,owned:[],stats:{deals:0,profit:0,flips:0,rentIncome:0},loans:[],rentOffers:[],notifications:[],staff:[],staffOffers:[],lastSeenAt:Date.now(),lastDayAt:Date.now(),filter:"الكل"});
let state=initial(),user=null,profile=null,signup=false,listings=[],selectedArea=null,selectedLbUser=null;

const regularAreas=[
 ["شبرا","شعبي",690000,7],["عين شمس","شعبي",520000,9],["المطرية","شعبي",560000,9],["المرج","شعبي",500000,10],["فيصل","متوسط",780000,8],["الهرم","متوسط",820000,8],["مدينة نصر","متوسط",1250000,6],["مصر الجديدة","فاخر",1850000,4],["المعادي","فاخر",1550000,5],["الزمالك","فاخر",3200000,8],["الدقي","فاخر",2350000,6],["المهندسين","فاخر",1900000,6],["العجوزة","فاخر",1800000,7],["عباس العقاد","متوسط",1350000,6],["القطامية","فاخر",2300000,8],["التجمع الخامس","فاخر",2200000,6],["الشيخ زايد","فاخر",2450000,7],["6 أكتوبر","متوسط",1050000,9],["الشروق","متوسط",1200000,8],["العبور","متوسط",950000,8],["بدر","متوسط",650000,10],["حدائق أكتوبر","متوسط",760000,10],["العاصمة الإدارية","استثماري",1750000,10],["مدينتي","فاخر",2650000,8],["الرحاب","فاخر",2500000,7],["زايد الجديدة","فاخر",3500000,10],["الإسكندرية","متوسط",950000,7],["سيدي بشر","متوسط",820000,8]
];
const coastal=[
 ["الساحل الشمالي","ساحلي",3200000,11,["مارينا 1","مارينا 2","مارينا 3","مارينا 4","مارينا 5","بورتو جولف","ستيلا","مراسي","هاسيندا","أمواج","تلال","فوكا باي","سيزر","غزالة باي","رأس الحكمة"]],
 ["العين السخنة","ساحلي",2400000,10,["بورتو السخنة","الجلالة","العين باي","لاجونا باي","بالم هيلز العين السخنة","أزها","مورانو","تلال السخنة","لافيستا","أويست"]],
 ["العلمين الجديدة","ساحلي",4100000,12,["مراسي العلمين","نورث إيدج","ذا جيت","مازارين","ممشى العلمين"]],
 ["الجونة","ساحلي",6200000,13,["الجونة","سوما باي"]]
];
const urbanTypes={
 "شعبي":[["استوديو","1 نوم","55م²",.62],["شقة","2 نوم","90م²",.82],["شقة","3 نوم","125م²",1],["شقة","3 نوم","140م²",1.08],["شقة","2 نوم","80م²",.75],["منزل","3 نوم","150م²",1.18]],
 "متوسط":[["استوديو","1 نوم","60م²",.65],["شقة","2 نوم","95م²",.85],["شقة","3 نوم","130م²",1],["شقة فاخرة","3 نوم","165م²",1.28],["دوبلكس","4 نوم","210م²",1.65],["بنتهاوس","4 نوم","230م²",1.9],["منزل","4 نوم","220م²",1.7]],
 "فاخر":[["شقة فاخرة","3 نوم","170م²",1.35],["دوبلكس","4 نوم","230م²",1.75],["بنتهاوس","4 نوم","280م²",2.2],["فيلا","4 نوم","300م²",2.55],["فيلا","5 نوم","380م²",3.05],["قصر","6 نوم","650م²",4.4],["شقة فاخرة","4 نوم","210م²",1.6]],
 "استثماري":[["شقة","2 نوم","90م²",.8],["شقة فاخرة","3 نوم","150م²",1.25],["دوبلكس","4 نوم","220م²",1.7],["بنتهاوس","4 نوم","280م²",2.15],["فيلا","5 نوم","350م²",2.9],["محل","تجاري","70م²",1.2]]
};
const sellers=["عم سيد","الحاج محمود","مدام نهى","أستاذ شريف","عماد","الحاج رضا","مدام داليا","عم حسن","مروان","ياسر"];
const tenants=["أحمد","محمد","محمود","عمر","سارة","نور","ياسين","كريم","ملك","عبدالله","علي","ريم"];
const staffRoles=[
 {role:"Sales Agent",name:"مندوب مبيعات",unlock:2000000,salary:25000,commission:.025,skill:42},
 {role:"Rental Agent",name:"مندوب تأجير",unlock:2000000,salary:22000,commission:.02,skill:48},
 {role:"Real Estate Broker",name:"وسيط عقاري",unlock:5000000,salary:45000,commission:.035,skill:58},
 {role:"Senior Broker",name:"وسيط أول",unlock:10000000,salary:75000,commission:.045,skill:68},
 {role:"Expert Agent",name:"خبير عقاري",unlock:20000000,salary:120000,commission:.055,skill:78}
];
const $=id=>document.getElementById(id), money=n=>`${Math.max(0,Math.round(Number(n)||0)).toLocaleString("en-US")} ج.م`, num=n=>Math.round(Number(n)||0).toLocaleString("en-US"), rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$("toast").classList.remove("show"),2600)}
function normalizeUsername(s){return s.trim().toLowerCase().replace(/\s+/g,"_")}
function validUsername(s){return /^[\p{L}\p{N}_-]{3,18}$/u.test(s)}
function authEmail(u){return normalizeUsername(u)+"@login.semsarmasr.local"}
function cloneInitial(){return initial()}
function netWorth(){return state.cash+state.owned.reduce((s,p)=>s+Number(p.currentValue||0),0)-state.loans.reduce((s,l)=>s+Number(l.remaining||0),0)}
function slots(){return 2+state.office*2}
function dayNow(){return Math.max(1,Number(state.day||1)+Math.floor(Math.max(0,Date.now()-Number(state.lastDayAt||Date.now()))/DAY_MS))}
function syncDay(){const now=Date.now(),last=Number(state.lastDayAt||now),passed=Math.floor(Math.max(0,now-last)/DAY_MS);if(passed>0){state.day=Math.max(1,Number(state.day||1)+passed);state.lastDayAt=last+passed*DAY_MS;state.notifications=state.notifications||[];state.notifications.unshift(`وصلت إلى اليوم ${state.day}.`);state.notifications=state.notifications.slice(0,12);return true}return false}
function dayStorageKey(){return user?`semsem_day_${user.id}`:null}
function loadDayClock(){const key=dayStorageKey();if(!key)return;try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Number.isFinite(Number(saved.day))&&Number.isFinite(Number(saved.lastDayAt))){state.day=Math.max(Number(state.day||1),Number(saved.day));state.lastDayAt=Number(saved.lastDayAt)}}catch{}syncDay();saveDayClock()}
function saveDayClock(){const key=dayStorageKey();if(!key)return;try{localStorage.setItem(key,JSON.stringify({day:Number(state.day||1),lastDayAt:Number(state.lastDayAt||Date.now())}))}catch{}}
function secondsIncome(){return state.owned.filter(p=>p.rentContract).reduce((s,p)=>s+Number(p.rentContract.monthly||0)/(30*24*3600),0)}
function applyOfflineIncome(){
 const now=Date.now(), rawLast=Number(state.lastSeenAt||now), last=Math.max(rawLast,now-RENT_OFFLINE_CAP_MS);
 let income=0;
 state.owned.forEach(p=>{if(!p.rentContract)return; const end=Number(p.rentContract.endAt||Infinity); const active=Math.max(0,Math.min(now,end)-Math.min(last,end)); income+=Number(p.rentContract.monthly||0)*active/(30*24*3600*1000)});
 if(income>0){state.cash+=Math.floor(income);state.stats.rentIncome=(state.stats.rentIncome||0)+Math.floor(income);state.notifications.unshift(`تحصيل إيجارات متراكمة: ${money(income)}.`);state.notifications=state.notifications.slice(0,12)}
 state.lastSeenAt=now; syncDay(); saveDayClock();
 return income;
}
async function saveCloud(){if(!sbReady||!user||!profile)return;const {error}=await sb.from("game_profiles").upsert({id:user.id,username:profile.username,cash:Math.round(state.cash),rep:state.rep,level:state.level,office:state.office,day:state.day,owned:state.owned,stats:state.stats,loans:state.loans,rent_offers:state.rentOffers,staff:state.staff,staff_offers:state.staffOffers,net_worth:Math.round(netWorth()),updated_at:new Date().toISOString()},{onConflict:"id"});if(error)console.error(error)}
async function loadCloud(){if(!sbReady)throw new Error("أضف Supabase URL و anon key في config.js.");const {data,error}=await sb.from("game_profiles").select("username,cash,rep,level,office,day,owned,stats,loans,rent_offers,staff,staff_offers").eq("id",user.id).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("الحساب مش موجود في قاعدة اللعبة.");profile={username:data.username};state={...cloneInitial(),cash:Number(data.cash),rep:Number(data.rep),level:Number(data.level),office:Number(data.office),day:Number(data.day),owned:Array.isArray(data.owned)?data.owned:[],stats:{...cloneInitial().stats,...(data.stats||{})},loans:Array.isArray(data.loans)?data.loans:[],rentOffers:Array.isArray(data.rent_offers)?data.rent_offers:[],staff:Array.isArray(data.staff)?data.staff:[],staffOffers:Array.isArray(data.staff_offers)?data.staff_offers:[],lastSeenAt:Date.now(),lastDayAt:Date.now()};loadDayClock()}
async function auth(){if(!sbReady){$("authMsg").textContent="تسجيل الدخول محتاج إعداد Supabase في config.js.";return}const raw=$("username").value.trim(),pass=$("password").value;if(!validUsername(raw))return $("authMsg").textContent="اسم المستخدم من 3 لـ18 حرف.";if(pass.length<6)return $("authMsg").textContent="كلمة السر لازم تكون 6 حروف على الأقل.";const username=normalizeUsername(raw),email=authEmail(username);$("authBtn").disabled=true;try{if(signup){const {data:a,error:ae}=await sb.rpc("username_available",{requested_username:username});if(ae)throw new Error(ae.message);if(!a)return $("authMsg").textContent="اسم المستخدم محجوز.";const {data,error}=await sb.auth.signUp({email,password:pass});if(error)throw new Error(error.message);if(!data.user)throw new Error("تعذر إنشاء الحساب.");user=data.user;profile={username};state=cloneInitial();saveDayClock();const {error:pe}=await sb.from("game_profiles").insert({id:user.id,username,cash:START_CASH,rep:18,level:1,office:1,day:1,owned:[],stats:state.stats,loans:[],rent_offers:[],staff:[],staff_offers:[],net_worth:START_CASH});if(pe){await sb.auth.signOut();throw new Error(pe.message)}if(data.session)await startGame();else $("authMsg").textContent="الحساب اتعمل. اقفل Confirm email من Supabase."}else{const {data,error}=await sb.auth.signInWithPassword({email,password:pass});if(error)throw new Error("اسم المستخدم أو كلمة السر غلط.");user=data.user;await startGame()}}catch(e){$("authMsg").textContent=e.message||"حصل خطأ."}finally{$("authBtn").disabled=false}}
async function startGame(){try{await loadCloud()}catch(e){$("authMsg").textContent=e.message;return}applyOfflineIncome();$("authScreen").classList.add("hidden");$("gameApp").classList.remove("hidden");$("playerName").textContent=profile.username;buildListings();render();await leaderboard()}
async function logout(){applyOfflineIncome();await saveCloud();if(sbReady)await sb.auth.signOut();location.reload()}
function areaAllows(a,type){const tier=a[1];if(type==="شاليه"||type==="Beach House"||type==="فيلا ساحلية")return tier==="ساحلي";return true}
function allAreas(){return [...regularAreas,...coastal.map(x=>[x[0],x[1],x[2],x[3],x[4]])]}
function makeRegularListings(){return regularAreas.flatMap((a,ai)=>Array.from({length:10},(_,i)=>{const pool=urbanTypes[a[1]]||urbanTypes["متوسط"],t=pool[(ai*3+i)%pool.length],estimate=Math.round(a[2]*t[3]*(.86+((i*7)%17)/100));const condition=58+((ai*11+i*7)%39),ask=Math.round(estimate*(.90+((i*5)%9)/100));return {id:`${slug(a[0])}-${i+1}`,area:a[0],areaType:a[1],type:t[0],rooms:t[1],size:t[2],estimate,ask,marketValue:estimate,condition,seller:sellers[(ai+i)%sellers.length],emoji:t[0].includes("فيلا")?"⌂":t[0].includes("قصر")?"♜":t[0].includes("محل")?"▣":"▤"}}))}
function makeCoastalListings(){const out=[];coastal.forEach((c,ci)=>c[4].forEach((v,vi)=>{for(let i=1;i<=10;i++){const base=Math.round(c[2]*(.82+vi*.025)*(1+i*.018)),ask=Math.round(base*(.91+((i+vi)%7)/100));out.push({id:`${slug(c[0])}-${slug(v)}-chalet-${i}`,area:c[0],village:v,areaType:"ساحلي",type:"شاليه",rooms:`${2+(i%3)} نوم`,size:`${105+i*5}م²`,estimate:base,ask,marketValue:base,condition:65+(i%31),seller:sellers[(i+vi)%sellers.length],emoji:"⌂"})}for(let i=1;i<=10;i++){const base=Math.round(c[2]*(1.55+vi*.04)*(1+i*.025)),ask=Math.round(base*(.92+((i+vi)%6)/100));out.push({id:`${slug(c[0])}-${slug(v)}-villa-${i}`,area:c[0],village:v,areaType:"ساحلي",type:"فيلا",rooms:`${4+(i%2)} نوم`,size:`${260+i*12}م²`,estimate:base,ask,marketValue:base,condition:70+(i%26),seller:sellers[(i+vi+3)%sellers.length],emoji:"⌂"})}}));return out}
function slug(s){return String(s).replace(/\s+/g,"-").replace(/[^\u0600-\u06FF\w-]/g,"")}
function buildListings(){const owned=new Set(state.owned.map(p=>p.id));listings=[...makeRegularListings(),...makeCoastalListings()].filter(p=>!owned.has(p.id));}
function render(){applyOfflineIncome();$("cash").textContent=money(state.cash);$("netWorth").textContent=money(netWorth());$("rep").textContent=`${num(state.rep)}/100`;$("level").textContent=num(state.level);$("day").textContent=num(dayNow());$("dateText").textContent=`السنة ${2026+Math.floor((dayNow()-1)/360)} • الشهر ${Math.floor(((dayNow()-1)%360)/30)+1} • اليوم ${((dayNow()-1)%30)+1}`;$("playerName").textContent=profile?.username||"لاعب";$("rentPerSecond").textContent=money(secondsIncome());$("rentPerHour").textContent=money(secondsIncome()*3600);$("rentPerDay").textContent=money(secondsIncome()*86400);$("loanDebt").textContent=money(state.loans.reduce((s,l)=>s+l.remaining,0));$("propertyCount").textContent=num(state.owned.length);$("staffCount").textContent=num(state.staff.length);$("profitTotal").textContent=money(state.stats.profit||0);$("notifBadge").textContent=num(state.notifications.length);renderListings();renderPortfolio();renderCities();renderBank();renderStaff();renderLeaderboardCached();renderProfile();renderTransactions();renderLoansSummary();}
function renderListings(){let data=listings;if(selectedArea){data=data.filter(p=>p.area===selectedArea.name&&(!selectedArea.village||p.village===selectedArea.village));$("marketTitle").textContent=selectedArea.village?`${selectedArea.village} — ${selectedArea.name}`:`${selectedArea.name}`;$("backMarket").classList.remove("hidden")}else{$("marketTitle").textContent="سوق العقارات";$("backMarket").classList.add("hidden")}if(state.filter&&state.filter!=="الكل")data=data.filter(p=>p.areaType===state.filter);$("listings").innerHTML=data.slice(0,80).map(p=>`<article class="property"><div class="pic"><span>${p.emoji}</span><small>${p.village||p.area}</small></div><div class="pbody"><div class="property-title"><h3>${escapeHtml(p.type)}</h3><span class="hot">${escapeHtml(p.areaType)}</span></div><div class="meta"><span class="tag">${escapeHtml(p.rooms)}</span><span class="tag">${escapeHtml(p.size)}</span><span class="tag">حالة ${p.condition}%</span></div><div class="price-row"><div><div class="price">${money(p.ask)}</div><div class="estimate">السوق ${money(p.marketValue)}</div></div><span class="deal">${Math.max(1,Math.round((p.marketValue-p.ask)/p.marketValue*100))}% تحت السوق</span></div><div class="actions"><button class="secondary-btn negotiate" data-id="${p.id}">فاوض</button><button class="primary-btn buy" data-id="${p.id}">شراء</button></div></div></article>`).join("")||`<div class="empty">مفيش عقارات ظاهرة هنا بالفلتر الحالي.</div>`;document.querySelectorAll(".buy").forEach(b=>b.onclick=()=>buy(b.dataset.id));document.querySelectorAll(".negotiate").forEach(b=>b.onclick=()=>negotiationModal(b.dataset.id))}
function renderPortfolio(){const offers=state.rentOffers||[];$("offerList").innerHTML=offers.map((o,i)=>`<div class="offer-card"><div><b>${escapeHtml(o.propertyName)}</b><small>${escapeHtml(o.tenant)} • عرض إيجار شهري</small></div><strong>${money(o.monthly)}</strong><button class="primary-btn rentAccept" data-i="${i}">قبول</button><button class="secondary-btn rentCounter" data-i="${i}">تفاوض</button><button class="ghost-btn rentReject" data-i="${i}">رفض</button></div>`).join("")||"";document.querySelectorAll(".rentAccept").forEach(b=>b.onclick=()=>acceptRent(+b.dataset.i));document.querySelectorAll(".rentCounter").forEach(b=>b.onclick=()=>counterRent(+b.dataset.i));document.querySelectorAll(".rentReject").forEach(b=>b.onclick=()=>rejectRent(+b.dataset.i));$("portfolioList").innerHTML=state.owned.map((p,i)=>{const r=p.rentContract;const accrued=r?Math.min(Date.now(),Number(r.endAt))-Number(p.lastRentCollected||r.startAt):0;const pending=r?Math.max(0,Math.floor(Number(r.monthly)*accrued/(30*24*3600*1000))):0;return `<article class="property owned-card"><div class="pic"><span>${p.emoji}</span><small>${r?"مؤجر":"شاغر"}</small></div><div class="pbody"><div class="property-title"><h3>${escapeHtml(p.type)} • ${escapeHtml(p.area)}${p.village?` • ${escapeHtml(p.village)}`:""}</h3><span class="hot">${r?"مؤجر":"متاح"}</span></div><div class="meta"><span class="tag">شراء ${money(p.buyPrice)}</span><span class="tag">قيمة ${money(p.currentValue)}</span></div><div class="mini-stats"><span>ربح <b>${money(p.currentValue-p.buyPrice)}</b></span>${r?`<span>إيجار <b>${money(r.monthly)}/شهر</b></span><span>متراكم الآن <b>${money(pending)}</b></span>`:"<span>في انتظار طلب تأجير</span>"}</div><div class="actions"><button class="secondary-btn rentMine" data-i="${i}">${r?"إدارة العقد":"طلب إيجار"}</button><button class="primary-btn sell" data-i="${i}">بيع</button></div></div></article>`}).join("")||`<div class="empty">لسه مفيش عقارات. السوق مستني أول صفقة.</div>`;document.querySelectorAll(".rentMine").forEach(b=>b.onclick=()=>rentalForProperty(+b.dataset.i));document.querySelectorAll(".sell").forEach(b=>b.onclick=()=>sell(+b.dataset.i))}
function negotiationModal(id){const p=listings.find(x=>x.id===id);if(!p)return;const floor=Math.round(p.marketValue*(.78+Math.min(state.rep,80)/1000));let value=Math.round(p.ask);openModal(`<h2>التفاوض على ${escapeHtml(p.type)}</h2><p>${escapeHtml(p.area)}${p.village?` • ${escapeHtml(p.village)}`:""}</p><div class="deal-box">السوق: <b>${money(p.marketValue)}</b><br>أقل سعر منطقي: <b>${money(floor)}</b><br><small>4 جولات كحد أقصى، وكل ما تبعد عن السوق تقل فرصة القبول.</small></div><div class="offer-price" id="negValue">${money(value)}</div><input class="range" id="negRange" type="range" min="${floor}" max="${p.ask}" value="${value}" step="1000"><button class="primary-btn wide" id="sendNeg">إرسال العرض</button>`);$("negRange").oninput=e=>$("negValue").textContent=money(e.target.value);$("sendNeg").onclick=async()=>{const offer=Number($("negRange").value);p.negotiationRounds=(p.negotiationRounds||0)+1;const chance=clamp(.28+(offer-p.marketValue*.78)/(p.marketValue*.22)*.5+state.rep/500,0,.82);if(Math.random()<chance){p.ask=Math.min(p.ask,offer);closeModal();toast(`البائع وافق على ${money(offer)}.`);await buy(p.id)}else if(p.negotiationRounds>=4){closeModal();toast("البائع رفض بعد آخر جولة.")}else{closeModal();toast("البائع رفض. حاول بعرض أقرب للسوق.")}await saveCloud();render()}}
async function buy(id){const p=listings.find(x=>x.id===id);if(!p)return;if(state.owned.some(x=>x.id===id))return toast("العقار ده موجود عندك بالفعل.");if(state.owned.length>=slots())return toast(`سعة مكتبك ${slots()} عقارات. طوّر المكتب.`);if(state.cash<p.ask)return toast("الكاش مش مكفي.");const price=Math.round(p.ask);state.cash-=price;const owned={...p,buyPrice:price,currentValue:Math.round(p.marketValue*(p.condition/100)*(1.01+Math.random()*.08)),rented:false,rentContract:null,lastRentCollected:Date.now()};state.owned.push(owned);listings=listings.filter(x=>x.id!==id);state.stats.deals++;state.rep=clamp(state.rep+1,0,100);if(state.stats.deals%4===0)state.level++;state.notifications.unshift(`اشتريت ${p.type} في ${p.village||p.area} مقابل ${money(price)}.`);await saveCloud();render();toast("تم شراء العقار.")}
async function sell(i){const p=state.owned[i];if(!p)return;if(p.rentContract)return toast("العقار مؤجر. لا يمكن بيعه أثناء العقد.");const sale=Math.round(p.currentValue),profit=sale-p.buyPrice;state.cash+=sale;state.stats.profit+=profit;state.stats.flips++;state.owned.splice(i,1);state.notifications.unshift(`تم بيع العقار مقابل ${money(sale)}.`);await saveCloud();buildListings();render();toast(`تم البيع وربحك ${money(profit)}.`)}
function rentalForProperty(i){const p=state.owned[i];if(!p)return;if(p.rentContract){openModal(`<h2>عقد الإيجار</h2><p>${escapeHtml(p.rentContract.tenant)} • ${money(p.rentContract.monthly)} شهريًا</p><div class="deal-box">ينتهي العقد: ${new Date(p.rentContract.endAt).toLocaleString("ar-EG")}<br>حد التجميع عند إغلاق اللعبة: 12 ساعة.</div><button class="primary-btn wide" onclick="closeModal()">إغلاق</button>`);return}const suggested=Math.max(5000,Math.round(p.currentValue*.006));openModal(`<h2>طلبات الإيجار</h2><p>${escapeHtml(p.type)} • ${escapeHtml(p.area)}</p><div class="deal-box">متوسط مقترح: <b>${money(suggested)} / شهر</b><br><small>الطلبات الوهمية هنا تتولد بشكل دوري، واللاعب يقدر يفاوض عليها.</small></div><button class="primary-btn wide" onclick="generateRentOffer(${i})">جلب عرض جديد</button>`)}
async function generateRentOffer(i){const p=state.owned[i];if(!p||p.rentContract)return;const base=Math.max(5000,Math.round(p.currentValue*.006));const offer={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),propertyId:p.id,propertyName:`${p.type} • ${p.area}`,tenant:tenants[rand(0,tenants.length-1)],monthly:Math.round(base*(.82+Math.random()*.32)),createdAt:Date.now()};state.rentOffers.unshift(offer);state.notifications.unshift(`وصل عرض إيجار جديد لعقار ${p.type}.`);await saveCloud();closeModal();render();toast("وصل عرض إيجار جديد.")}
async function acceptRent(i){const o=state.rentOffers[i];if(!o)return;const p=state.owned.find(x=>x.id===o.propertyId);if(!p)return;const now=Date.now();p.rentContract={tenant:o.tenant,monthly:o.monthly,startAt:now,endAt:now+30*24*3600*1000};p.lastRentCollected=now;state.rentOffers.splice(i,1);state.notifications.unshift(`تم تأجير العقار لـ${o.tenant} بسعر ${money(o.monthly)} شهريًا.`);await saveCloud();render();toast("تم قبول الإيجار.")}
async function rejectRent(i){state.rentOffers.splice(i,1);await saveCloud();render();toast("تم رفض العرض.")}
async function counterRent(i){const o=state.rentOffers[i];if(!o)return;openModal(`<h2>تفاوض على الإيجار</h2><p>العرض الحالي: ${money(o.monthly)} / شهر</p><input id="counterRentValue" class="text-input" type="number" min="1" value="${Math.round(o.monthly*1.12)}"><button class="primary-btn wide" id="counterRentBtn">إرسال</button>`);$("counterRentBtn").onclick=async()=>{const v=Number($("counterRentValue").value);if(v<=0)return;if(Math.random()<clamp(.72-(v/o.monthly-1)*2.5,.18,.78)){o.monthly=v;closeModal();await acceptRent(i)}else{closeModal();state.rentOffers.splice(i,1);await saveCloud();render();toast("المستأجر رفض العرض المضاد.")}}}
function renderCities(){const regular=regularAreas.map(a=>`<button class="city" data-area="${escapeAttr(a[0])}"><div class="city-top"><span class="tier">${a[1]}</span><span>10 عقارات</span></div><h3>${escapeHtml(a[0])}</h3><p>متوسط السوق يبدأ من ${money(a[2])}</p></button>`).join("");const coast=coastal.map(c=>`<button class="city coastal-card" data-coast="${escapeAttr(c[0])}"><div class="city-top"><span class="tier">ساحلي</span><span>${c[4].length} قرية</span></div><h3>${escapeHtml(c[0])}</h3><p>قرى ومنتجعات، وكل قرية فيها 10 شاليهات + 10 فلل.</p></button>`).join("");$("cityGrid").innerHTML=regular+coast;document.querySelectorAll("[data-area]").forEach(b=>b.onclick=()=>{selectedArea={name:b.dataset.area};showTab("market")});document.querySelectorAll("[data-coast]").forEach(b=>b.onclick=()=>coastalModal(b.dataset.coast))}
function coastalModal(name){const c=coastal.find(x=>x[0]===name);if(!c)return;const villageCards=c[4].map((v,vi)=>`<button class="village" data-village="${escapeAttr(v)}"><b>${escapeHtml(v)}</b><small>20 عقار متاح</small><small>10 شاليهات + 10 فلل</small><span class="village-enter">دخول القرية ←</span></button>`).join("");openModal(`<h2>${escapeHtml(name)}</h2><p>اختار القرية أو المنتجع. كل قرية لها سوق مستقل.</p><div class="village-grid">${villageCards}</div>`);document.querySelectorAll("[data-village]").forEach(b=>b.onclick=()=>{closeModal();selectedArea={name,village:b.dataset.village};showTab("market");renderListings()})}
function renderBank(){const debt=state.loans.reduce((s,l)=>s+Number(l.remaining||0),0);$("bankList").innerHTML=state.loans.map((l,i)=>`<div class="bank-loan"><div><b>${money(l.remaining)} متبقي</b><small>الأصل ${money(l.amount)} • فائدة ${l.rate}% • القسط ${money(l.installment)}</small><small>موعد القسط: ${new Date(l.nextPayment).toLocaleDateString("ar-EG")}</small></div><button class="primary-btn payLoan" data-i="${i}">سداد قسط</button></div>`).join("")||`<div class="empty">مفيش قروض حالية. القروض الجديدة مرتبطة بثروتك ومش هتديك مبلغ خيالي.</div>`;$("debtTotal").textContent=money(debt);$("loanCount").textContent=num(state.loans.length);document.querySelectorAll(".payLoan").forEach(b=>b.onclick=()=>payLoan(+b.dataset.i))}
function loanLimit(){return Math.min(20000000,Math.max(100000,Math.floor((netWorth()*.22)*(1+state.level*.025))))}
function loanModal(){const limit=loanLimit();if(limit<100000)return toast("محتاج تبني ثروة أكتر قبل أول قرض.");openModal(`<h2>طلب قرض</h2><p>الحد الحالي حسب ثروتك: <b>${money(limit)}</b></p><input id="loanValue" class="text-input" type="number" min="100000" max="${limit}" value="${Math.min(500000,limit)}"><div class="deal-box">الفائدة تتراوح حسب مستوى اللاعب، والقسط الشهري هيظهر قبل التأكيد.</div><button class="primary-btn wide" id="takeLoan">تأكيد القرض</button>`);$("takeLoan").onclick=takeLoan}
async function takeLoan(){const limit=loanLimit(),amount=Math.round(Number($("loanValue").value));if(amount<100000||amount>limit)return toast("المبلغ خارج الحد المسموح.");if(state.loans.length>=3)return toast("ممنوع أكثر من 3 قروض في نفس الوقت.");const rate=9+Math.min(7,state.level*.45),months=12,interest=amount*rate/100,total=Math.round(amount+interest),loan={id:String(Date.now()),amount,rate:Number(rate.toFixed(1)),remaining:total,monthsLeft:months,installment:Math.ceil(total/months),nextPayment:Date.now()+30*24*3600*1000};state.cash+=amount;state.loans.push(loan);state.notifications.unshift(`تم صرف قرض ${money(amount)} بفائدة ${rate.toFixed(1)}%.`);await saveCloud();closeModal();render();toast("تم صرف القرض.")}
async function payLoan(i){const l=state.loans[i];if(!l)return;if(state.cash<l.installment)return toast("الكاش مش مكفي للقسط.");state.cash-=l.installment;l.remaining=Math.max(0,l.remaining-l.installment);l.monthsLeft--;l.nextPayment=Date.now()+30*24*3600*1000;if(l.remaining<=0||l.monthsLeft<=0){state.loans.splice(i,1);toast("تم سداد القرض بالكامل.")}else toast("تم دفع القسط.");await saveCloud();render()}
function renderStaff(){const nw=netWorth();$("staffList").innerHTML=staffRoles.map((r,idx)=>{const owned=state.staff.find(s=>s.role===r.role);return `<div class="staff-card"><div class="staff-avatar">${idx+1}</div><div><h3>${r.name}</h3><p>${r.role} • فتح عند ${money(r.unlock)}</p><small>راتب ${money(r.salary)} • عمولة ${(r.commission*100).toFixed(1)}% • مهارة ${r.skill}%</small></div>${owned?`<button class="secondary-btn fireStaff" data-id="${owned.id}">إدارة</button>`:`<button class="primary-btn hireStaff" data-role="${r.role}" ${nw<r.unlock?"disabled":""}>توظيف</button>`}</div>`}).join("");document.querySelectorAll(".hireStaff").forEach(b=>b.onclick=()=>hireStaff(b.dataset.role));document.querySelectorAll(".fireStaff").forEach(b=>b.onclick=()=>manageStaff(b.dataset.id))}
async function hireStaff(role){const r=staffRoles.find(x=>x.role===role);if(!r)return;if(netWorth()<r.unlock)return toast(`الموظف ده يفتح عند ${money(r.unlock)} صافي ثروة.`);if(state.staff.length>=5)return toast("الحد الأقصى 5 موظفين.");const s={id:String(Date.now()),role:r.role,name:r.name,level:"Junior",salary:r.salary,commission:r.commission,skill:r.skill,assignedPropertyId:null,lastSalaryAt:Date.now()};state.staff.push(s);state.notifications.unshift(`تم توظيف ${r.name}.`);await saveCloud();render();toast("تم التوظيف.")}
function manageStaff(id){const s=state.staff.find(x=>x.id===id),r=staffRoles.find(x=>x.role===s.role);if(!s)return;openModal(`<h2>${escapeHtml(s.name)}</h2><p>${s.role} • ${s.level}</p><div class="deal-box">راتب ${money(s.salary)} • عمولة ${(s.commission*100).toFixed(1)}%<br>مهارة ${s.skill}%</div><select id="staffProperty" class="text-input"><option value="">بدون عقار</option>${state.owned.map(p=>`<option value="${p.id}" ${s.assignedPropertyId===p.id?"selected":""}>${escapeHtml(p.type)} • ${escapeHtml(p.area)}</option>`).join("")}</select><div class="actions"><button class="primary-btn" id="saveStaff">حفظ</button><button class="secondary-btn" id="upgradeStaff">ترقية</button><button class="ghost-btn" id="fireStaff">فصل</button></div>`);$("saveStaff").onclick=async()=>{s.assignedPropertyId=$("staffProperty").value||null;await saveCloud();closeModal();render();toast("تم تحديث الموظف.")};$("upgradeStaff").onclick=async()=>{if(s.level==="Junior"){s.level="Intermediate";s.skill+=8;s.salary=Math.round(s.salary*1.25);s.commission+=.005}else if(s.level==="Intermediate"){s.level="Senior";s.skill+=8;s.salary=Math.round(s.salary*1.3);s.commission+=.005}else{s.level="Expert";s.skill=Math.min(92,s.skill+7);s.salary=Math.round(s.salary*1.3);s.commission+=.005}await saveCloud();closeModal();render();toast("تمت ترقية الموظف.")};$("fireStaff").onclick=async()=>{state.staff=state.staff.filter(x=>x.id!==id);await saveCloud();closeModal();render();toast("تم فصل الموظف.")}}
function processStaff(){state.staff.forEach(s=>{const r=staffRoles.find(x=>x.role===s.role);const weeks=Math.floor((Date.now()-Number(s.lastSalaryAt||Date.now()))/(7*24*3600*1000));if(weeks>0){state.cash-=weeks*s.salary;s.lastSalaryAt=Date.now();state.notifications.unshift(`تم خصم ${money(weeks*s.salary)} رواتب للموظفين.`)}if(s.assignedPropertyId&&Math.random()<s.skill/100*.18){const p=state.owned.find(x=>x.id===s.assignedPropertyId);if(p&&!p.rentContract&&(s.role!=="Sales Agent"||Math.random()<.5)){const offer={id:String(Date.now()+Math.random()),propertyId:p.id,propertyName:`${p.type} • ${p.area}`,tenant:tenants[rand(0,tenants.length-1)],monthly:Math.round(Math.max(5000,p.currentValue*.006)*(0.9+Math.random()*.2)),createdAt:Date.now(),source:"staff"};state.rentOffers.unshift(offer);state.notifications.unshift(`${s.name} جاب عرض تأجير جديد.`)}}});state.notifications=state.notifications.slice(0,12)}
function renderLeaderboardCached(){if(!$("lb"))return;$("lb").innerHTML="<div class='empty'>اضغط تحديث لعرض المتصدرين.</div>"}
async function leaderboard(){if(!sbReady)return;const {data,error}=await sb.rpc("get_leaderboard");if(error){console.error(error);return}$("lb").innerHTML=(data||[]).map((p,i)=>`<button class="lb-row ${p.username===profile?.username?"me":""}" data-user="${escapeAttr(p.username)}"><span class="lb-rank">#${i+1}</span><span class="lb-name">${escapeHtml(p.username)}</span><span class="lb-money">${money(p.net_worth)}</span><span class="arrow">›</span></button>`).join("")||`<div class='empty'>لسه مفيش لاعبين.</div>`;document.querySelectorAll(".lb-row").forEach(b=>b.onclick=()=>publicProfile(b.dataset.user))}
async function publicProfile(username){if(!sbReady)return;const {data,error}=await sb.rpc("get_public_player",{requested_username:username});if(error||!data?.length)return toast("مش قادر أجيب البروفايل دلوقتي.");const p=data[0];openModal(`<h2>${escapeHtml(p.username)}</h2><div class="profile-public"><div><small>الترتيب</small><b>#${p.rank||"—"}</b></div><div><small>صافي الثروة</small><b>${money(p.net_worth)}</b></div><div><small>العقارات</small><b>${num(p.property_count)}</b></div><div><small>إجمالي الربح</small><b>${money(p.total_profit)}</b></div><div><small>الرتبة</small><b>${escapeHtml(p.rank_name)}</b></div></div>`)}
function renderProfile(){const rank=state.level>=12?"بارون العقارات":state.level>=8?"مليونير السوق":state.level>=4?"سمسار تقيل":"سمسار مبتدئ";$("rankName").textContent=rank;$("statsText").textContent=`${num(state.stats.deals)} صفقة • ${num(state.stats.flips)} بيع • ربح ${money(state.stats.profit)}`;$("achievements").innerHTML=[[
 state.stats.deals>=1,"أول صفقة","اشتريت أول عقار"],[state.owned.length>=5,"محفظة محترمة","امتلك 5 عقارات"],[netWorth()>=2000000,"دخلت نادي الموظفين","صافي ثروة 2 مليون"],[state.loans.length>0,"استفدت من البنك","أول قرض"],[secondsIncome()>0,"مالك مؤجر","عندك دخل إيجار"],[state.level>=10,"مليونير السوق","مستوى 10"]].map(a=>`<div class="achievement ${a[0]?"":"off"}"><b>${a[1]}</b><small>${a[2]}</small></div>`).join("")}
function renderTransactions(){const list=(state.notifications||[]).slice(0,10);$("activityList").innerHTML=list.map(x=>`<div class="activity-item">${escapeHtml(x)}</div>`).join("")||`<div class="empty">مفيش نشاط لسه.</div>`}
function renderLoansSummary(){}
async function upgradeOffice(){const cost=Math.round(750000*Math.pow(2,state.office-1));if(state.cash<cost)return toast(`تطوير المكتب محتاج ${money(cost)} كاش.`);state.cash-=cost;state.office++;state.notifications.unshift(`تم تطوير المكتب للمستوى ${state.office}.`);await saveCloud();render();toast("تم تطوير المكتب.")}

function showTab(id){document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===id));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===id));window.scrollTo({top:0,behavior:"smooth"})}
function openModal(html){$("modalContent").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function escapeAttr(s){return escapeHtml(s)}

$("authBtn")?.addEventListener("click",auth);
$("loginTab")?.addEventListener("click",()=>{signup=false;$("loginTab").classList.add("active");$("signupTab")?.classList.remove("active");$("authBtn").textContent="دخول"});
$("signupTab")?.addEventListener("click",()=>{signup=true;$("signupTab").classList.add("active");$("loginTab")?.classList.remove("active");$("authBtn").textContent="إنشاء حساب"});
$("logoutBtn")?.addEventListener("click",logout);
$("loanBtn2")?.addEventListener("click",loanModal);
$("hireBtn")?.addEventListener("click",()=>showTab("staff"));
$("upgradeBtn")?.addEventListener("click",upgradeOffice);
$("refreshLb")?.addEventListener("click",leaderboard);
$("closeModal")?.addEventListener("click",closeModal);
$("modal")?.addEventListener("click",e=>{if(e.target===$("modal"))closeModal()});
$("backMarket")?.addEventListener("click",()=>{selectedArea=null;renderListings()});
$("clearNotifs")?.addEventListener("click",()=>{state.notifications=[];render()});
$("notifBtn")?.addEventListener("click",()=>$("notificationsPanel")?.classList.toggle("hidden"));
document.querySelectorAll(".tab").forEach(t=>t.addEventListener("click",()=>showTab(t.dataset.tab)));
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{state.filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderListings()}));
function updateOfficeUI(){if($("officeLevel"))$("officeLevel").textContent=num(state.office);if($("officeSlots"))$("officeSlots").textContent=num(slots());if($("upgradeBtn"))$("upgradeBtn").textContent=`تطوير — ${money(Math.round(750000*Math.pow(2,state.office-1)))}`}
const _render=render; render=()=>{_render();updateOfficeUI()};

setInterval(async()=>{if(!user)return;const changed=syncDay();render();if(changed){saveDayClock();await saveCloud()}},1000);
setInterval(async()=>{if(!user)return;processStaff();applyOfflineIncome();if(state.rentOffers.length<3&&Math.random()<.12&&state.owned.some(p=>!p.rentContract))await generateRentOffer(state.owned.findIndex(p=>!p.rentContract));render();await saveCloud();saveDayClock()},60000);
