-- سمسار مصر — FINAL schema
create table if not exists public.game_profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text not null unique,
 cash bigint not null default 500000,
 rep integer not null default 18,
 level integer not null default 1,
 office integer not null default 1,
 day integer not null default 1,
 owned jsonb not null default '[]'::jsonb,
 stats jsonb not null default '{"deals":0,"profit":0,"flips":0,"rentIncome":0}'::jsonb,
 loans jsonb not null default '[]'::jsonb,
 rent_offers jsonb not null default '[]'::jsonb,
 staff jsonb not null default '[]'::jsonb,
 staff_offers jsonb not null default '[]'::jsonb,
 net_worth bigint not null default 500000,
 updated_at timestamptz not null default now()
);
alter table public.game_profiles enable row level security;
create index if not exists game_profiles_net_worth_idx on public.game_profiles(net_worth desc);
drop policy if exists "read own profile" on public.game_profiles;
drop policy if exists "insert own profile" on public.game_profiles;
drop policy if exists "update own profile" on public.game_profiles;
create policy "read own profile" on public.game_profiles for select to authenticated using (auth.uid()=id);
create policy "insert own profile" on public.game_profiles for insert to authenticated with check (auth.uid()=id);
create policy "update own profile" on public.game_profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);
create or replace function public.username_available(requested_username text) returns boolean language sql security definer set search_path=public as $$ select not exists(select 1 from public.game_profiles where lower(username)=lower(trim(requested_username))); $$;
drop function if exists public.get_leaderboard();
create function public.get_leaderboard() returns table(username text,net_worth bigint) language sql security definer set search_path=public as $$ select gp.username,gp.net_worth from public.game_profiles gp order by gp.net_worth desc limit 50; $$;
drop function if exists public.get_public_player(text);
create function public.get_public_player(requested_username text) returns table(username text,net_worth bigint,property_count integer,total_profit bigint,rank_name text,rank bigint) language sql security definer set search_path=public as $$
 select gp.username,gp.net_worth,jsonb_array_length(gp.owned)::integer,coalesce((gp.stats->>'profit')::bigint,0),case when gp.level>=12 then 'بارون العقارات' when gp.level>=8 then 'مليونير السوق' when gp.level>=4 then 'سمسار تقيل' else 'سمسار مبتدئ' end,(select count(*)+1 from public.game_profiles x where x.net_worth>gp.net_worth) from public.game_profiles gp where lower(gp.username)=lower(trim(requested_username)) limit 1; $$;
grant execute on function public.username_available(text) to anon,authenticated;
grant execute on function public.get_leaderboard() to authenticated;
grant execute on function public.get_public_player(text) to authenticated;

-- ADMIN CONTROL CENTER
alter table public.game_profiles add column if not exists is_admin boolean not null default false;
alter table public.game_profiles add column if not exists is_banned boolean not null default false;

create table if not exists public.admin_action_log (
 id bigint generated by default as identity primary key,
 admin_id uuid not null references auth.users(id) on delete cascade,
 target_id uuid references auth.users(id) on delete set null,
 action text not null,
 amount bigint,
 details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);
alter table public.admin_action_log enable row level security;
drop policy if exists "admins read action log" on public.admin_action_log;
create policy "admins read action log" on public.admin_action_log for select to authenticated using (exists(select 1 from public.game_profiles gp where gp.id=auth.uid() and gp.is_admin=true));

create or replace function public.admin_list_players()
returns table(id uuid,username text,cash bigint,net_worth bigint,level integer,property_count integer,is_admin boolean,is_banned boolean)
language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.game_profiles where game_profiles.id=auth.uid() and game_profiles.is_admin=true) then raise exception 'غير مصرح'; end if;
 return query select gp.id,gp.username,gp.cash,gp.net_worth,gp.level,jsonb_array_length(coalesce(gp.owned,'[]'::jsonb))::integer,gp.is_admin,gp.is_banned from public.game_profiles gp order by gp.net_worth desc;
end; $$;


create or replace function public.admin_give_money(target_id uuid, amount bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
 if amount<=0 or amount>100000000000 then raise exception 'المبلغ غير صالح'; end if;
 update public.game_profiles set cash=cash+amount, net_worth=net_worth+amount, updated_at=now() where id=target_id;
 if not found then raise exception 'اللاعب غير موجود'; end if;
 insert into public.admin_action_log(admin_id,target_id,action,amount) values(auth.uid(),target_id,'give_money',amount);
 return true;
end; $$;

create or replace function public.admin_remove_money(target_id uuid, amount bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
 if amount<=0 or amount>100000000000 then raise exception 'المبلغ غير صالح'; end if;
 update public.game_profiles set cash=greatest(0,cash-amount), net_worth=greatest(0,net_worth-amount), updated_at=now() where id=target_id;
 if not found then raise exception 'اللاعب غير موجود'; end if;
 insert into public.admin_action_log(admin_id,target_id,action,amount) values(auth.uid(),target_id,'remove_money',amount);
 return true;
end; $$;

create or replace function public.admin_ban_player(target_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
 if target_id=auth.uid() then raise exception 'لا يمكنك حظر نفسك'; end if;
 update public.game_profiles set is_banned=true, updated_at=now() where id=target_id;
 if not found then raise exception 'اللاعب غير موجود'; end if;
 insert into public.admin_action_log(admin_id,target_id,action) values(auth.uid(),target_id,'ban');
 return true;
end; $$;

create or replace function public.admin_unban_player(target_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
 update public.game_profiles set is_banned=false, updated_at=now() where id=target_id;
 if not found then raise exception 'اللاعب غير موجود'; end if;
 insert into public.admin_action_log(admin_id,target_id,action) values(auth.uid(),target_id,'unban');
 return true;
end; $$;

create or replace function public.admin_reset_player(target_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
 if target_id=auth.uid() then raise exception 'لا يمكنك تصفير حساب الأدمن من هنا'; end if;
 update public.game_profiles set cash=500000,rep=18,level=1,office=1,day=1,owned='[]'::jsonb,stats='{"deals":0,"profit":0,"flips":0}'::jsonb,loans='[]'::jsonb,staff='[]'::jsonb,staff_offers='[]'::jsonb,net_worth=500000,updated_at=now() where id=target_id;
 if not found then raise exception 'اللاعب غير موجود'; end if;
 insert into public.admin_action_log(admin_id,target_id,action) values(auth.uid(),target_id,'reset');
 return true;
end; $$;

grant execute on function public.admin_list_players() to authenticated;
grant execute on function public.admin_give_money(uuid,bigint) to authenticated;
grant execute on function public.admin_remove_money(uuid,bigint) to authenticated;
grant execute on function public.admin_ban_player(uuid) to authenticated;
grant execute on function public.admin_unban_player(uuid) to authenticated;
grant execute on function public.admin_reset_player(uuid) to authenticated;

