-- سمسار مصر — FINAL schema
create table if not exists public.game_profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text not null unique,
 cash bigint not null default 500000,
 rep integer not null default 18,
 level integer not null default 1,
 office integer not null default 1,
 day integer not null default 1,
 owned jsonb not null default '[]'::jsonb,
 stats jsonb not null default '{"deals":0,"profit":0,"flips":0,"rentIncome":0}'::jsonb,
 loans jsonb not null default '[]'::jsonb,
 rent_offers jsonb not null default '[]'::jsonb,
 staff jsonb not null default '[]'::jsonb,
 staff_offers jsonb not null default '[]'::jsonb,
 net_worth bigint not null default 500000,
 updated_at timestamptz not null default now()
);
alter table public.game_profiles enable row level security;
create index if not exists game_profiles_net_worth_idx on public.game_profiles(net_worth desc);
drop policy if exists "read own profile" on public.game_profiles;
drop policy if exists "insert own profile" on public.game_profiles;
drop policy if exists "update own profile" on public.game_profiles;
create policy "read own profile" on public.game_profiles for select to authenticated using (auth.uid()=id);
create policy "insert own profile" on public.game_profiles for insert to authenticated with check (auth.uid()=id);
create policy "update own profile" on public.game_profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);
create or replace function public.username_available(requested_username text) returns boolean language sql security definer set search_path=public as $$ select not exists(select 1 from public.game_profiles where lower(username)=lower(trim(requested_username))); $$;
drop function if exists public.get_leaderboard();
create function public.get_leaderboard() returns table(username text,net_worth bigint) language sql security definer set search_path=public as $$ select gp.username,gp.net_worth from public.game_profiles gp order by gp.net_worth desc limit 50; $$;
drop function if exists public.get_public_player(text);
create function public.get_public_player(requested_username text) returns table(username text,net_worth bigint,property_count integer,total_profit bigint,rank_name text,rank bigint) language sql security definer set search_path=public as $$
 select gp.username,gp.net_worth,jsonb_array_length(gp.owned)::integer,coalesce((gp.stats->>'profit')::bigint,0),case when gp.level>=12 then 'بارون العقارات' when gp.level>=8 then 'مليونير السوق' when gp.level>=4 then 'سمسار تقيل' else 'سمسار مبتدئ' end,(select count(*)+1 from public.game_profiles x where x.net_worth>gp.net_worth) from public.game_profiles gp where lower(gp.username)=lower(trim(requested_username)) limit 1; $$;
grant execute on function public.username_available(text) to anon,authenticated;
grant execute on function public.get_leaderboard() to authenticated;
grant execute on function public.get_public_player(text) to authenticated;

-- ADMIN TOOLS
alter table public.game_profiles add column if not exists is_admin boolean not null default false;
alter table public.game_profiles add column if not exists is_banned boolean not null default false;

drop table if exists public.admin_action_log;
create table if not exists public.admin_action_log (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete cascade,
  target_id uuid references auth.users(id) on delete set null,
  action text not null,
  amount bigint,
  created_at timestamptz not null default now()
);
alter table public.admin_action_log enable row level security;
drop policy if exists "admin read logs" on public.admin_action_log;
create policy "admin read logs" on public.admin_action_log for select to authenticated using (exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true));

drop function if exists public.get_my_ban_status();
create function public.get_my_ban_status() returns table(is_banned boolean) language sql security definer set search_path=public as $$
  select coalesce(gp.is_banned,false) from public.game_profiles gp where gp.id=auth.uid() limit 1;
$$;
grant execute on function public.get_my_ban_status() to authenticated;

create or replace function public.admin_list_players()
returns table(id uuid, username text, cash bigint, net_worth bigint, level integer, property_count integer, is_admin boolean, is_banned boolean)
language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.game_profiles where game_profiles.id=auth.uid() and game_profiles.is_admin=true) then
    raise exception 'غير مصرح';
  end if;
  return query select gp.id,gp.username,gp.cash,gp.net_worth,gp.level,jsonb_array_length(coalesce(gp.owned,'[]'::jsonb))::integer,gp.is_admin,gp.is_banned
  from public.game_profiles gp order by gp.net_worth desc;
end; $$;
grant execute on function public.admin_list_players() to authenticated;

create or replace function public.admin_give_money(p_id uuid, amount bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
  if amount is null or amount <= 0 then raise exception 'مبلغ غير صالح'; end if;
  update public.game_profiles set cash=cash+amount, net_worth=net_worth+amount, updated_at=now() where id=p_id;
  if not found then raise exception 'اللاعب غير موجود'; end if;
  insert into public.admin_action_log(admin_id,target_id,action,amount) values(auth.uid(),p_id,'give_money',amount);
  return true;
end; $$;
grant execute on function public.admin_give_money(uuid,bigint) to authenticated;

create or replace function public.admin_remove_money(p_id uuid, amount bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
  if amount is null or amount <= 0 then raise exception 'مبلغ غير صالح'; end if;
  update public.game_profiles set cash=greatest(0,cash-amount), net_worth=greatest(0,net_worth-amount), updated_at=now() where id=p_id;
  if not found then raise exception 'اللاعب غير موجود'; end if;
  insert into public.admin_action_log(admin_id,target_id,action,amount) values(auth.uid(),p_id,'remove_money',amount);
  return true;
end; $$;
grant execute on function public.admin_remove_money(uuid,bigint) to authenticated;

create or replace function public.admin_ban_player(p_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
  if p_id=auth.uid() then raise exception 'لا يمكنك حظر حسابك'; end if;
  update public.game_profiles set is_banned=true, updated_at=now() where id=p_id;
  if not found then raise exception 'اللاعب غير موجود'; end if;
  insert into public.admin_action_log(admin_id,target_id,action) values(auth.uid(),p_id,'ban');
  return true;
end; $$;
grant execute on function public.admin_ban_player(uuid) to authenticated;

create or replace function public.admin_unban_player(p_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
  update public.game_profiles set is_banned=false, updated_at=now() where id=p_id;
  if not found then raise exception 'اللاعب غير موجود'; end if;
  insert into public.admin_action_log(admin_id,target_id,action) values(auth.uid(),p_id,'unban');
  return true;
end; $$;
grant execute on function public.admin_unban_player(uuid) to authenticated;

create or replace function public.admin_reset_player(p_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.game_profiles where id=auth.uid() and is_admin=true) then raise exception 'غير مصرح'; end if;
  update public.game_profiles set cash=500000,net_worth=500000,rep=18,level=1,office=1,day=1,owned='[]'::jsonb,stats='{"deals":0,"profit":0,"flips":0}'::jsonb,loans='[]'::jsonb,staff='[]'::jsonb,staff_offers='[]'::jsonb,updated_at=now() where id=p_id;
  if not found then raise exception 'اللاعب غير موجود'; end if;
  insert into public.admin_action_log(admin_id,target_id,action) values(auth.uid(),p_id,'reset');
  return true;
end; $$;
grant execute on function public.admin_reset_player(uuid) to authenticated;
